main: awzaw\antispampro\AntiSpamPro
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: POSTWORLD
name: VMAnti
description: "Blocks: Advertising, spamming, and swearing."
version: 1.0.0
author: awzaw
commands:
 anti:
  permission: anti.command
  description: "Change VM Anti Settings"
  usage: "/anti [help || kick || ban || set <cooldown in secs)>]"
permissions:
  anti:
   default: op
   description: "Allows access to all ANTI commands and bypass filter"
   children:
    anti.command:
     default: op
     description: "Allows access to all ANTI commands"
    anti.bypass:
     default: op
     description: "Allows user to bypass ANTI filter"
